$(document).ready(function(){
  $(".faq1").click(function(){
      $(".faqp1").toggle(10);
  });
});
$(document).ready(function(){
  $(".faq2").click(function(){
      $(".faqp2").toggle(10);
  });
});
$(document).ready(function(){
  $(".faq3").click(function(){
      $(".faqp3").toggle(10);
  });
});
$(document).ready(function(){
  $(".faq4").click(function(){
      $(".faqp4").toggle(10);
  });
});
$(document).ready(function(){
  $(".faq5").click(function(){
      $(".faqp5").toggle(10);
  });
});
$(document).ready(function(){
  $(".faq6").click(function(){
      $(".faqp6").toggle(10);
  });
});